module.exports = {
	PIZZA: 'pizza',
	ATM: 'atm',
	TAXI: 'taxi',
	ENTRANCE: 'entrance',
	EXIT: 'exit',
	HOTDOG_HAMBURGER: 'hotdog_hamburger',
	MEXICAN: 'mexican',
	GYROS: 'gyros',
	HEALTHY_FOOD: 'healthy_food',
	CAMPING: 'camping',
	WC: 'wc',
	SUPERMARKET: 'supermarket',
	FISH: 'fish',
	BREAKFAST: 'breakfast',
	PIZZA: 'pizza',
	PARKING: 'parking',
	TOBACCO: 'tobacco',
	BEER: 'beer',
	WINE: 'wine',
	COCKTAILS: 'cocktails',
	WHISKY: 'whisky',
	COFFEE: 'coffee',
	LOCKERS: 'lockers',
	CHARGING_STATION: 'charging_station',
	FIRST_AID: 'first-aid',
	INFORMATION: 'information',
};
