module.exports = {
	SET_CONTEXT: 'SET_CONTEXT',
	SEND_REPLY: 'SEND_REPLY',
	SEND_QUICK_REPLY: 'SEND_QUICK_REPLY',
	SEND_BUTTONS: 'SEND_BUTTONS',
	SEND_LOGIN_BUTTON: 'SEND_LOGIN_BUTTON',
	GET_FACEBOOK_DATA: 'GET_FACEBOOK_DATA',
	GET_SPOTIFY_ARTISTS: 'GET_SPOTIFY_ARTISTS',
};
